services:
  magang-franken:
    container_name: magang-franken
    image: image_magang-franken
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/app
    env_file:
      - .env