services:
  # SERVICE 1: Untuk melayani request web
  magang-franken:
    container_name: magang-franken
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/app
    networks:
      - default
      - mysql-stack_mysql_network

  # SERVICE 2: Untuk menjalankan antrian (QUEUE WORKER)
  magang-worker:
    container_name: magang-worker
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work --sleep=3 --tries=3
    volumes:
      - .:/app
    networks:
      - default
      - mysql-stack_mysql_network

networks:
  default:
  mysql-stack_mysql_network:
    external: true
